apiVersion: apps/v1
kind: Deployment
metadata:
 name: bbb-deployment
spec:
 selector:
   matchLabels:
    type: backend
 replicas: 1
 template:
   metadata:
     labels:
       type: backend
   spec:
    containers:
    - name: backend-container
      image: gedflow/back:latesttt
      ports:
      - containerPort: 8000
      envFrom:
      - configMapRef:
          name: cm-mysql
      - secretRef:
          name: sec-mysql
